/**
 * Florence Academy NGN unfolding cases - loader.
 *
 * The data (150 cases + their 900 Clinical-Judgment items, section 17) is
 * auto-generated by scripts/import_content_banks.py from the owned case-set
 * .docx volumes and shipped as hashed JSON assets (src/assets/banks/cases.json,
 * case-items.json). It is fetched on demand by `loadCaseBank()` when an
 * unfolding-case session starts, so none of it is bundled into the Practice
 * route chunk. Each case is a shared scenario (tabs) + 6 items referenced in
 * order by `questionIds`; items are played within the case runner, NOT mixed
 * into the adaptive question pool. Regenerate from source - do not hand-edit.
 */

import type { CaseStudy, Question } from "../types/question";
import manifest from "./bankManifest.json";
import casesUrl from "../assets/banks/cases.json?url";
import caseItemsUrl from "../assets/banks/case-items.json?url";

/** Case count, kept synchronous for the landing page (no fetch). */
export const CASE_COUNT = manifest.cases;

export interface CaseBank {
  cases: CaseStudy[];
  items: Question[];
}

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to load case bank (HTTP ${res.status}): ${url}`);
  }
  return (await res.json()) as T;
}

let cache: CaseBank | null = null;
let inflight: Promise<CaseBank> | null = null;

/** The loaded case bank if it is already available (synchronous; no fetch). */
export function loadedCaseBank(): CaseBank | null {
  return cache;
}

/**
 * Fetch the unfolding-case bank on demand. Memoized - concurrent and repeat
 * callers share one fetch; a failed load is not cached, so a retry refetches.
 */
export function loadCaseBank(): Promise<CaseBank> {
  if (cache) return Promise.resolve(cache);
  if (!inflight) {
    inflight = Promise.all([
      fetchJson<CaseStudy[]>(casesUrl),
      fetchJson<Question[]>(caseItemsUrl),
    ])
      .then(([cases, items]) => {
        cache = { cases, items };
        inflight = null;
        return cache;
      })
      .catch((err) => {
        inflight = null;
        throw err;
      });
  }
  return inflight;
}
