/**
 * Florence Academy seed question bank.
 *
 * IMPORTANT - provenance: every item here is ORIGINAL, Florence-authored or
 * deterministically generated from factual reference data (normal lab ranges,
 * dosage arithmetic). None of it is transcribed from UWorld / Archer / Saunders
 * / Klimek or any other commercial bank. Those remain topical reference only.
 *
 * Two parts:
 *   1. `HAND_ITEMS`  - hand-authored showcase items, one+ of every NCLEX item
 *                      type, spread across Client-Need categories and Sections.
 *   2. generators    - `genLabItems()` and `genDosageItems()` produce a large,
 *                      blueprint-tagged, difficulty-calibrated pool from facts
 *                      so the nightly 150-item mode has real volume.
 *
 * The combined `QUESTION_BANK` exceeds 150 items so a full nightly CAT session
 * can run. It is a SEED to be expanded with Florence-owned content.
 */

import {
  type Question,
  type MultipleChoiceQuestion,
  type FillInBlankQuestion,
} from "../types/question";
import { LAB_GROUPS } from "./labValues";
import manifest from "./bankManifest.json";

// Florence-owned banks, auto-generated by the importer scripts. Each ships as
// its own hashed JSON asset (src/assets/banks/*.json) and is fetched on demand
// at session start via `loadQuestionBank()` - NONE of this payload is bundled
// into the Practice route chunk, so first paint stays fast as the pool grows.
import importedUrl from "../assets/banks/imported.json?url";
import fabUrl from "../assets/banks/fab.json?url";
import bowtieUrl from "../assets/banks/bowtie.json?url";
import dragDropUrl from "../assets/banks/dragdrop.json?url";
import extendedMrUrl from "../assets/banks/extended-mr.json?url";
import sataUrl from "../assets/banks/sata.json?url";

// ---------------------------------------------------------------------------
// 1. Hand-authored showcase items - every item type
// ---------------------------------------------------------------------------

const HAND_ITEMS: Question[] = [
  {
    id: "mc-nitro-hold",
    type: "multiple-choice",
    difficulty: -0.5,
    clientNeed: "pharmacological-therapies",
    section: 7,
    topic: "Angina / nitrates",
    cjmm: "take-actions",
    stem: "A client with acute chest pain has an order for sublingual nitroglycerin. Which finding requires the nurse to withhold the next dose?",
    options: [
      "A throbbing headache",
      "Systolic blood pressure of 88 mmHg",
      "Heart rate of 72/min",
      "Partial relief of chest pain",
    ],
    correct: 1,
    rationale:
      "Nitroglycerin is a vasodilator and lowers blood pressure. Hold the dose for a systolic BP below 90 mmHg. Headache is an expected, benign effect of vasodilation.",
    reference: "Field Guide · Cardiac",
  },
  {
    id: "mc-dig-tox",
    type: "multiple-choice",
    difficulty: 0.3,
    clientNeed: "pharmacological-therapies",
    section: 3,
    topic: "Digoxin toxicity",
    cjmm: "analyze-cues",
    stem: "A client takes digoxin daily. Which finding is an early indicator of digoxin toxicity?",
    options: [
      "Anorexia, nausea, and vomiting",
      "Hyperkalemia",
      "Bounding peripheral pulses",
      "Hypertension",
    ],
    correct: 0,
    rationale:
      "Gastrointestinal symptoms (anorexia, nausea, vomiting) are common early signs of digoxin toxicity. Visual changes (yellow-green halos) and dysrhythmias follow. Hypokalemia - not hyperkalemia - potentiates toxicity.",
    reference: "Field Guide · Pharmacology I",
  },
  {
    id: "sata-acs",
    type: "select-all",
    difficulty: 0.5,
    clientNeed: "reduction-of-risk",
    section: 7,
    topic: "Acute coronary syndrome",
    cjmm: "generate-solutions",
    stem: "A client arrives with suspected acute coronary syndrome. Which interventions should the nurse anticipate? Select all that apply.",
    options: [
      "Obtain a 12-lead ECG",
      "Administer chewable aspirin 325 mg",
      "Apply supplemental oxygen if SpO₂ is below 94%",
      "Encourage the client to ambulate in the hallway",
      "Establish intravenous access",
    ],
    correct: [0, 1, 2, 4],
    rationale:
      "Early ACS care includes a 12-lead ECG, aspirin, oxygen titrated to keep SpO₂ ≥ 94%, and IV access. The client should rest - ambulation increases myocardial oxygen demand.",
    reference: "Field Guide · Cardiac",
  },
  {
    id: "fib-metoprolol",
    type: "fill-in-blank",
    difficulty: -0.6,
    clientNeed: "pharmacological-therapies",
    section: 4,
    topic: "Dosage calculation",
    stem: "A prescription reads metoprolol 50 mg PO. Available: 25 mg scored tablets. How many tablets should the nurse administer? (Record a number.)",
    answer: 2,
    unit: "tablets",
    tolerance: 0,
    decimals: 0,
    rationale: "Tablets = desired ÷ available = 50 mg ÷ 25 mg = 2 tablets.",
  },
  {
    id: "fib-heparin-rate",
    type: "fill-in-blank",
    difficulty: 0.9,
    clientNeed: "pharmacological-therapies",
    section: 4,
    topic: "IV infusion rate",
    stem: "Heparin 25,000 units in 250 mL of D5W is prescribed to infuse at 1,000 units/hr. At how many mL/hr should the nurse set the infusion pump? (Record a number.)",
    answer: 10,
    unit: "mL/hr",
    tolerance: 0,
    decimals: 0,
    rationale:
      "Concentration = 25,000 units ÷ 250 mL = 100 units/mL. Rate = 1,000 units/hr ÷ 100 units/mL = 10 mL/hr.",
  },
  {
    id: "order-race",
    type: "ordered-response",
    difficulty: 0.2,
    clientNeed: "safety-infection-control",
    section: 15,
    topic: "Fire safety (RACE)",
    cjmm: "take-actions",
    stem: "A fire breaks out in a client's room. Place the nurse's actions in the correct order using the RACE protocol.",
    steps: [
      "Rescue any client in immediate danger",
      "Activate the fire alarm",
      "Confine the fire by closing doors and windows",
      "Extinguish the fire or evacuate the area",
    ],
    rationale:
      "RACE: Rescue, Alarm, Confine, Extinguish/Evacuate. Client safety (rescue) comes first, then alerting others.",
    reference: "Field Guide · Infection Control & Safety",
  },
  {
    id: "matrix-drug-class",
    type: "matrix",
    difficulty: -0.3,
    clientNeed: "pharmacological-therapies",
    section: 3,
    topic: "Drug classifications",
    mode: "single",
    stem: "For each medication, select its drug classification.",
    rows: ["Furosemide", "Metoprolol", "Warfarin", "Digoxin"],
    columns: [
      "Loop diuretic",
      "Beta-adrenergic blocker",
      "Anticoagulant",
      "Cardiac glycoside",
    ],
    correct: [[0], [1], [2], [3]],
    rationale:
      "Furosemide = loop diuretic; metoprolol = beta blocker; warfarin = anticoagulant; digoxin = cardiac glycoside.",
  },
  {
    id: "cloze-abg",
    type: "dropdown-cloze",
    difficulty: 0.8,
    clientNeed: "physiological-adaptation",
    section: 8,
    topic: "ABG interpretation",
    cjmm: "analyze-cues",
    stem: "Use the ABG results to complete the statement: pH 7.30, PaCO₂ 52 mmHg, HCO₃⁻ 24 mEq/L.",
    segments: [
      { kind: "text", text: "The client is experiencing " },
      {
        kind: "blank",
        options: [
          "respiratory acidosis",
          "respiratory alkalosis",
          "metabolic acidosis",
        ],
        correct: 0,
      },
      { kind: "text", text: " that is " },
      {
        kind: "blank",
        options: ["uncompensated", "fully compensated"],
        correct: 0,
      },
      { kind: "text", text: "." },
    ],
    rationale:
      "Low pH with an elevated PaCO₂ indicates respiratory acidosis. The HCO₃⁻ is still normal (22-26), so there is no metabolic compensation yet - uncompensated.",
    reference: "Field Guide · Respiratory",
  },
  {
    id: "highlight-deterioration",
    type: "highlight",
    difficulty: 0.6,
    clientNeed: "reduction-of-risk",
    section: 7,
    topic: "Recognizing deterioration",
    cjmm: "recognize-cues",
    instruction:
      "Highlight each assessment finding that requires immediate follow-up.",
    stem: "Review the nurse's assessment of a post-operative client.",
    tokens: [
      "Temperature 37.1°C",
      "Heart rate 128/min and irregular",
      "Blood pressure 86/50 mmHg",
      "Reports crushing substernal chest pain",
      "Oxygen saturation 91% on room air",
      "Capillary refill 2 seconds",
    ],
    correct: [1, 2, 3, 4],
    rationale:
      "Tachycardia with an irregular rhythm, hypotension, chest pain, and hypoxemia all require immediate follow-up. A temperature of 37.1°C and a 2-second capillary refill are normal.",
    reference: "Field Guide · Cardiac",
  },
  {
    id: "bowtie-shock",
    type: "bowtie",
    difficulty: 1.0,
    clientNeed: "physiological-adaptation",
    section: 7,
    topic: "Hypovolemic shock",
    cjmm: "take-actions",
    stem: "A post-operative client has a blood pressure of 84/52 mmHg, heart rate 122/min, and urine output of 15 mL/hr. Complete the bow-tie.",
    condition: {
      options: ["Hypovolemic shock", "Anaphylaxis", "Neurogenic shock"],
      correct: 0,
    },
    actions: {
      options: [
        "Administer an isotonic IV fluid bolus",
        "Position supine with legs elevated",
        "Restrict all IV fluids",
        "Administer an antihypertensive",
      ],
      correct: [0, 1],
    },
    parameters: {
      options: [
        "Blood pressure",
        "Urine output",
        "Deep tendon reflexes",
        "Hemoglobin A1C",
      ],
      correct: [0, 1],
    },
    rationale:
      "Hypotension, tachycardia, and oliguria point to hypovolemic shock. Restore volume with isotonic fluids and improve perfusion by elevating the legs, then monitor blood pressure and urine output for response.",
  },
  {
    id: "dragdrop-antidotes",
    type: "drag-drop",
    difficulty: 0.4,
    clientNeed: "pharmacological-therapies",
    section: 5,
    topic: "Reversal agents",
    stem: "Match each medication to its reversal agent / antidote.",
    zones: [
      { id: "warfarin", label: "Warfarin" },
      { id: "heparin", label: "Heparin" },
      { id: "opioids", label: "Opioids" },
      { id: "benzos", label: "Benzodiazepines" },
    ],
    tokens: [
      { id: "vitk", text: "Vitamin K", correctZone: "warfarin" },
      { id: "protamine", text: "Protamine sulfate", correctZone: "heparin" },
      { id: "naloxone", text: "Naloxone", correctZone: "opioids" },
      { id: "flumazenil", text: "Flumazenil", correctZone: "benzos" },
    ],
    rationale:
      "Vitamin K reverses warfarin; protamine sulfate reverses heparin; naloxone reverses opioids; flumazenil reverses benzodiazepines.",
  },
  {
    id: "trend-shock",
    type: "trend",
    difficulty: 0.7,
    clientNeed: "physiological-adaptation",
    section: 7,
    topic: "Trending vital signs",
    cjmm: "evaluate-outcomes",
    stem: "Review the client's vital-sign trend over six hours, then answer the question.",
    table: {
      columns: ["Time", "HR", "BP", "RR", "SpO₂"],
      rows: [
        ["08:00", "88", "120/80", "18", "97%"],
        ["10:00", "104", "108/74", "22", "95%"],
        ["12:00", "118", "96/60", "26", "91%"],
        ["14:00", "130", "84/50", "30", "88%"],
      ],
    },
    options: [
      "The client is improving and needs no change in care",
      "The client is deteriorating toward shock and needs rapid intervention",
      "The values are all within normal limits",
      "The trend indicates an allergic reaction",
    ],
    correct: 1,
    rationale:
      "Rising heart rate and respiratory rate with falling blood pressure and SpO₂ describe progressive decompensation (shock). This requires rapid escalation, not reassurance.",
  },
  {
    id: "mc-tb-precautions",
    type: "multiple-choice",
    difficulty: -0.8,
    clientNeed: "safety-infection-control",
    section: 15,
    topic: "Transmission precautions",
    stem: "Which precautions are required for a client with active pulmonary tuberculosis?",
    options: ["Contact", "Droplet", "Airborne", "Standard only"],
    correct: 2,
    rationale:
      "Tuberculosis spreads by airborne droplet nuclei. Use an airborne-infection isolation room (negative pressure) and an N95 respirator.",
    reference: "Field Guide · Infection Control & Safety",
  },
  {
    id: "mc-therapeutic-comm",
    type: "multiple-choice",
    difficulty: 0.2,
    clientNeed: "psychosocial-integrity",
    section: 14,
    topic: "Therapeutic communication",
    cjmm: "take-actions",
    stem: "A client newly diagnosed with cancer says, 'There's no point in any of this.' Which response is most therapeutic?",
    options: [
      "Don't give up hope - there are many treatments now.",
      "You sound discouraged. Tell me more about what you're feeling.",
      "Everyone feels this way at first; it passes.",
      "Let's focus on your treatment schedule instead.",
    ],
    correct: 1,
    rationale:
      "Reflecting the client's feeling and inviting them to say more is open-ended and therapeutic. The other options offer false reassurance, minimize, or change the subject.",
  },
  {
    id: "mc-hep-b-birth",
    type: "multiple-choice",
    difficulty: -0.7,
    clientNeed: "health-promotion",
    section: 13,
    topic: "Immunization schedule",
    stem: "Which immunization is routinely administered to a newborn before discharge?",
    options: [
      "Measles-mumps-rubella (MMR)",
      "Hepatitis B",
      "Varicella",
      "Diphtheria-tetanus-acellular pertussis (DTaP)",
    ],
    correct: 1,
    rationale:
      "The first hepatitis B dose is recommended at birth. MMR and varicella begin at 12 months; DTaP begins at 2 months.",
    reference: "Field Guide · Pediatrics",
  },
  {
    id: "sata-delegation",
    type: "select-all",
    difficulty: 0.6,
    clientNeed: "management-of-care",
    section: 16,
    topic: "Delegation to UAP",
    cjmm: "prioritize-hypotheses",
    stem: "Which tasks can the RN appropriately delegate to unlicensed assistive personnel (UAP)? Select all that apply.",
    options: [
      "Measuring and recording vital signs on a stable client",
      "Assisting a stable client with ambulation",
      "Performing the admission assessment",
      "Recording oral intake and output",
      "Developing the client's plan of care",
    ],
    correct: [0, 1, 3],
    rationale:
      "UAP may perform standardized, predictable tasks (vital signs, ambulation, I&O). Assessment and care planning require nursing judgment and cannot be delegated.",
    reference: "Field Guide · Management of Care",
  },
];

// ---------------------------------------------------------------------------
// 2a. Generated lab-interpretation items (from factual reference ranges)
// ---------------------------------------------------------------------------

const GROUP_DIFFICULTY: Record<string, number> = {
  Electrolytes: -1.0,
  "Renal & glucose": -0.8,
  Hematology: -0.7,
  Coagulation: 0.2,
  "Arterial blood gas": 0.9,
  Hepatic: 0.3,
  "Therapeutic drug levels": 1.0,
};

const decimalsOf = (n: number) => {
  const s = String(n);
  const i = s.indexOf(".");
  return i === -1 ? 0 : s.length - i - 1;
};
const round = (v: number, dp: number) => Number(v.toFixed(dp));
const slug = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

type LabVariant = "below" | "normal" | "above";
const VARIANT_LABEL: Record<LabVariant, string> = {
  below: "below the normal range",
  normal: "within normal limits",
  above: "above the normal range",
};

function genLabItems(): MultipleChoiceQuestion[] {
  const items: MultipleChoiceQuestion[] = [];
  const options = [
    "Below normal limits",
    "Within normal limits",
    "Above normal limits",
  ];

  for (const group of LAB_GROUPS) {
    const base = GROUP_DIFFICULTY[group.group] ?? 0;
    for (const lab of group.values) {
      if (lab.low === null || lab.high === null) continue;
      const { low, high } = lab;
      const dp = Math.min(2, Math.max(decimalsOf(low), decimalsOf(high)));
      const delta = high - low;
      const variants: { v: LabVariant; value: number; offset: number }[] = [
        { v: "below", value: round(low - delta * 0.4, dp), offset: 0.2 },
        { v: "normal", value: round((low + high) / 2, dp), offset: -0.3 },
        { v: "above", value: round(high + delta * 0.4, dp), offset: 0.1 },
      ];
      for (const { v, value, offset } of variants) {
        const correct = v === "below" ? 0 : v === "normal" ? 1 : 2;
        const unit = lab.unit ? ` ${lab.unit}` : "";
        items.push({
          id: `lab-${slug(lab.name)}-${v}`,
          type: "multiple-choice",
          difficulty: base + offset,
          clientNeed: "reduction-of-risk",
          section: 6,
          topic: `Lab values · ${group.group}`,
          stem: `A client's ${lab.name} result is ${value}${unit}. How should the nurse interpret this value?`,
          options,
          correct,
          rationale: `The normal reference range for ${lab.name} is ${low}-${high}${unit}. A result of ${value}${unit} is ${VARIANT_LABEL[v]}.`,
          reference: "Field Guide · Lab Values",
        });
      }
    }
  }
  return items;
}

// ---------------------------------------------------------------------------
// 2b. Generated dosage-calculation items (computable answers)
// ---------------------------------------------------------------------------

interface OralDrug {
  name: string;
  strength: number;
  unit: string;
  scored: boolean;
}
const ORAL_DRUGS: OralDrug[] = [
  { name: "furosemide", strength: 20, unit: "mg", scored: true },
  { name: "metoprolol", strength: 25, unit: "mg", scored: true },
  { name: "prednisone", strength: 10, unit: "mg", scored: true },
  { name: "lisinopril", strength: 10, unit: "mg", scored: true },
  { name: "levothyroxine", strength: 50, unit: "mcg", scored: true },
  { name: "carvedilol", strength: 12.5, unit: "mg", scored: true },
  { name: "hydralazine", strength: 25, unit: "mg", scored: true },
  { name: "amoxicillin", strength: 250, unit: "mg", scored: false },
  { name: "acetaminophen", strength: 500, unit: "mg", scored: false },
  { name: "metformin", strength: 500, unit: "mg", scored: false },
];

function difficultyForTabs(count: number): number {
  if (count === 1) return -1.0;
  if (count === 2) return -0.4;
  if (count === 3) return 0.1;
  return 0.5; // 0.5-tablet
}

function genDosageItems(): FillInBlankQuestion[] {
  const items: FillInBlankQuestion[] = [];
  let i = 0;
  for (const drug of ORAL_DRUGS) {
    const counts = drug.scored ? [0.5, 1, 2, 3] : [1, 2, 3];
    for (const count of counts) {
      const order = round(drug.strength * count, 3);
      const section = [3, 4, 5][i % 3];
      i++;
      items.push({
        id: `dose-${drug.name}-${String(count).replace(".", "_")}`,
        type: "fill-in-blank",
        difficulty: difficultyForTabs(count),
        clientNeed: "pharmacological-therapies",
        section,
        topic: "Dosage calculation",
        stem: `A prescription reads ${drug.name} ${order} ${drug.unit} PO. Available: ${drug.strength} ${drug.unit} ${
          drug.scored ? "scored tablets" : "tablets"
        }. How many tablets should the nurse administer? (Record a number.)`,
        answer: count,
        unit: "tablets",
        tolerance: 0,
        decimals: count % 1 === 0 ? 0 : 1,
        rationale: `Tablets = desired ÷ available = ${order} ${drug.unit} ÷ ${drug.strength} ${drug.unit} = ${count}.`,
      });
    }
  }

  // A few IV-rate / weight-based items with clean computed answers.
  const iv: Omit<FillInBlankQuestion, "type" | "clientNeed" | "topic">[] = [
    {
      id: "iv-1000-8h",
      difficulty: 0.3,
      section: 4,
      stem: "An IV of 1,000 mL of 0.9% saline is prescribed to infuse over 8 hours. At how many mL/hr should the pump be set? (Record a number.)",
      answer: 125,
      unit: "mL/hr",
      tolerance: 0,
      decimals: 0,
      rationale: "1,000 mL ÷ 8 hr = 125 mL/hr.",
    },
    {
      id: "iv-2L-10h",
      difficulty: 0.3,
      section: 4,
      stem: "Two liters of lactated Ringer's are prescribed over 10 hours. At how many mL/hr should the pump be set? (Record a number.)",
      answer: 200,
      unit: "mL/hr",
      tolerance: 0,
      decimals: 0,
      rationale: "2 L = 2,000 mL ÷ 10 hr = 200 mL/hr.",
    },
    {
      id: "iv-abx-30min",
      difficulty: 0.6,
      section: 4,
      stem: "An antibiotic in 100 mL is prescribed to infuse over 30 minutes. At how many mL/hr should the pump be set? (Record a number.)",
      answer: 200,
      unit: "mL/hr",
      tolerance: 0,
      decimals: 0,
      rationale: "100 mL ÷ 0.5 hr = 200 mL/hr.",
    },
    {
      id: "iv-gtt-15",
      difficulty: 1.1,
      section: 4,
      stem: "Infuse 500 mL over 4 hours using tubing with a drop factor of 15 gtt/mL. What is the flow rate in gtt/min? (Round to the nearest whole number.)",
      answer: 31,
      unit: "gtt/min",
      tolerance: 1,
      decimals: 0,
      rationale:
        "500 mL ÷ 4 hr = 125 mL/hr. (125 mL/hr × 15 gtt/mL) ÷ 60 min = 31.25 ≈ 31 gtt/min.",
    },
    {
      id: "wt-vanc",
      difficulty: 0.7,
      section: 5,
      stem: "Vancomycin is prescribed at 15 mg/kg for an 80 kg client. What is the total dose in mg? (Record a number.)",
      answer: 1200,
      unit: "mg",
      tolerance: 0,
      decimals: 0,
      rationale: "15 mg/kg × 80 kg = 1,200 mg.",
    },
    {
      id: "wt-acetaminophen-peds",
      difficulty: 0.6,
      section: 5,
      stem: "Acetaminophen is prescribed at 15 mg/kg for a 20 kg child. What is the dose in mg? (Record a number.)",
      answer: 300,
      unit: "mg",
      tolerance: 0,
      decimals: 0,
      rationale: "15 mg/kg × 20 kg = 300 mg.",
    },
    {
      id: "iv-insulin-drip",
      difficulty: 0.5,
      section: 5,
      stem: "An insulin drip of 100 units in 100 mL of saline is prescribed at 6 units/hr. At how many mL/hr should the pump be set? (Record a number.)",
      answer: 6,
      unit: "mL/hr",
      tolerance: 0,
      decimals: 0,
      rationale:
        "Concentration = 100 units ÷ 100 mL = 1 unit/mL. 6 units/hr ÷ 1 unit/mL = 6 mL/hr.",
    },
    {
      id: "iv-heparin-2",
      difficulty: 1.0,
      section: 5,
      stem: "Heparin 20,000 units in 500 mL of D5W is prescribed at 800 units/hr. At how many mL/hr should the pump be set? (Record a number.)",
      answer: 20,
      unit: "mL/hr",
      tolerance: 0,
      decimals: 0,
      rationale:
        "Concentration = 20,000 units ÷ 500 mL = 40 units/mL. 800 units/hr ÷ 40 units/mL = 20 mL/hr.",
    },
  ];

  for (const item of iv) {
    items.push({
      ...item,
      type: "fill-in-blank",
      clientNeed: "pharmacological-therapies",
      topic: "Dosage calculation",
    });
  }

  return items;
}

// ---------------------------------------------------------------------------
// Assembled bank
//
// The CORE items (hand-authored + generated) are small and stay in the bundle so
// a session can always start. The large Florence-owned banks are fetched on
// demand and folded in by `loadQuestionBank()`, then de-duped by id (first
// occurrence wins) so the CAT engine's answered-id tracking stays 1:1 even if
// two banks ever share an id.
// ---------------------------------------------------------------------------

// IEN US drug-naming module (Initiative 3 - start). Internationally-educated
// nurses (esp. India / UK-system corridors) learned drugs under British Approved
// Names; the NCLEX uses US generic names, so a wrong-name recognition error is a
// pure translation failure. Tagged lens:"drug_naming" + corridor:["india"] so the
// mastery model + remediation can target them. (Verify pairings before scaling.)
function genDrugNamingItems(): MultipleChoiceQuestion[] {
  const pairs: [string, string, [string, string, string]][] = [
    ["Paracetamol", "Acetaminophen", ["Ibuprofen", "Aspirin", "Naproxen"]],
    ["Salbutamol", "Albuterol", ["Ipratropium", "Levalbuterol", "Tiotropium"]],
    ["Frusemide", "Furosemide", ["Hydrochlorothiazide", "Spironolactone", "Bumetanide"]],
    ["Adrenaline", "Epinephrine", ["Norepinephrine", "Dopamine", "Atropine"]],
    ["Noradrenaline", "Norepinephrine", ["Epinephrine", "Phenylephrine", "Vasopressin"]],
    ["Glyceryl trinitrate (GTN)", "Nitroglycerin", ["Isosorbide mononitrate", "Hydralazine", "Nifedipine"]],
    ["Lignocaine", "Lidocaine", ["Amiodarone", "Procainamide", "Adenosine"]],
    ["Pethidine", "Meperidine", ["Morphine", "Hydromorphone", "Fentanyl"]],
    ["Rifampicin", "Rifampin", ["Isoniazid", "Ethambutol", "Pyrazinamide"]],
    ["Soluble insulin", "Regular insulin", ["Insulin glargine", "Insulin aspart", "NPH insulin"]],
  ];
  return pairs.map(([intl, us, distractors], i): MultipleChoiceQuestion => {
    // Deterministic option order (correct slot rotates by index - no RNG).
    const correct = i % 4;
    const options = [...distractors];
    options.splice(correct, 0, us);
    return {
      id: `drugname-${i + 1}`,
      type: "multiple-choice",
      difficulty: -0.5,
      clientNeed: "pharmacological-therapies",
      section: 3,
      topic: "US drug naming",
      lens: "drug_naming",
      corridor: ["india"],
      stem: `A medication you know as "${intl}" is ordered. Which US generic name refers to the SAME drug?`,
      options,
      correct,
      rationale: `"${intl}" is the British Approved / international name; the US generic name is ${us}. US MARs and the NCLEX use US generic names, so recognize the conversion on sight.`,
    };
  });
}

export const CORE_ITEMS: Question[] = [
  ...HAND_ITEMS,
  ...genLabItems(),
  ...genDosageItems(),
  ...genDrugNamingItems(),
];

/**
 * Size of the full adaptive pool, kept as a synchronous constant for the landing
 * page: CORE items plus each generated bank's count from the build-time manifest.
 * The runtime loader re-dedups by id; ids are unique across banks, so this equals
 * the loaded pool's length.
 */
export const BANK_SIZE =
  CORE_ITEMS.length +
  manifest.imported +
  manifest.fab +
  manifest.bowtie +
  manifest.dragdrop +
  manifest.extendedMr +
  manifest.sata;

// Fetched in this order so de-dup's "first occurrence wins" matches the old
// static assembly (CORE first, then imported → … → sata).
const BANK_URLS = [
  importedUrl,
  fabUrl,
  bowtieUrl,
  dragDropUrl,
  extendedMrUrl,
  sataUrl,
];

async function fetchBank(url: string): Promise<Question[]> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to load question bank (HTTP ${res.status}): ${url}`);
  }
  return (await res.json()) as Question[];
}

function dedupById(items: Question[]): Question[] {
  const seen = new Set<string>();
  const out: Question[] = [];
  for (const q of items) {
    if (seen.has(q.id)) continue;
    seen.add(q.id);
    out.push(q);
  }
  return out;
}

let pool: Question[] | null = null;
let inflight: Promise<Question[]> | null = null;

/** The assembled pool if it is already loaded (synchronous; no fetch). */
export function loadedQuestionBank(): Question[] | null {
  return pool;
}

/**
 * Assemble the full adaptive pool: CORE items plus every generated bank, fetched
 * on demand and de-duped by id. Memoized - concurrent and repeat callers share a
 * single fetch; a failed load is not cached, so a later retry refetches.
 */
export function loadQuestionBank(): Promise<Question[]> {
  if (pool) return Promise.resolve(pool);
  if (!inflight) {
    inflight = Promise.all(BANK_URLS.map(fetchBank))
      .then((banks) => {
        pool = dedupById([...CORE_ITEMS, ...banks.flat()]);
        inflight = null;
        return pool;
      })
      .catch((err) => {
        inflight = null;
        throw err;
      });
  }
  return inflight;
}
